# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@2.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build:
    docker:
      - image: cimg/android:2023.02.1-ndk

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: Get external module dependencies
          command: |
            ./scripts/install_modules.sh

      # And finally run the release build
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleFullRelease
            apksigner sign --key platform_build/target/product/security/platform.pk8 \
                --cert platform_build/target/product/security/platform.x509.pem \
                --in app/build/outputs/apk/full/release/app-full-release-unsigned.apk \
                --out app/build/outputs/apk/full/release/pico-tts-release.apk
      - store_artifacts:
          path: app/build/outputs/apk/full/release/pico-tts-release.apk
          destination: release

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
